export const metadata = {
  title: "OIC-student",
  description: "Generated by Sanada-Factory",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
