import "./globals.css";
import React from "react";
import Header from "../components/Header";

export const metadata = {
  title: "OIC-student",
  description: "Generated by Sanada-Factory",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="min-h-screen">
        {/* 固定ヘッダー */}
        <Header />

        {/* ヘッダーの高さ分下げる */}
        <div className="pt-16">{children}</div>
        {/*フッター*/}
        <footer className="w-full text-center py-4 bg-gray-100 text-gray-600 mt-8">&copy; SANDA-FACTORY</footer>
      </body>
    </html>
  );
}
